# QUESTION 2

In [2]:
#Question 2(a)
import numpy as np
a = (1,1,0)
a = np.array(a)
b = (0,1,1)
b = np.array(b)
2*a - 3*b

array([ 2, -1, -3])

In [3]:
#Question 2(b)
c = np.concatenate((a,b),axis = None)
c

array([1, 1, 0, 0, 1, 1])

In [4]:
#Question 2(c)
d = np.array((a[1],b[1],b[2]))
d

array([1, 1, 1])

In [5]:
#Question 2(d)
dist = np.linalg.norm(a-b)
dist

1.4142135623730951

In [6]:
#Question 2(e)
f = a+b
e = a-b
rad = np.arccos((np.dot(f,e))/((np.linalg.norm(f))*(np.linalg.norm(e))))
theta = (rad*180)/(np.pi)
theta

90.0

# QUESTION 3

In [7]:
A = np.random.rand(3,3)
A

array([[0.670147  , 0.63123193, 0.3906184 ],
       [0.40581501, 0.65376357, 0.1349363 ],
       [0.42172806, 0.98982685, 0.30812991]])

In [9]:
# Question 3(a) - Symmetric Matrix
A1 = (A+A.T)/2
A1

array([[0.670147  , 0.51852347, 0.40617323],
       [0.51852347, 0.65376357, 0.56238157],
       [0.40617323, 0.56238157, 0.30812991]])

In [10]:
A1[[0,2]][:,[0,2]]

array([[0.670147  , 0.40617323],
       [0.40617323, 0.30812991]])

In [11]:
#Question 3(b) - Skew- Symmetric Matrix
A2 = (A-A.T)/2
A2

array([[ 0.        ,  0.11270846, -0.01555483],
       [-0.11270846,  0.        , -0.42744527],
       [ 0.01555483,  0.42744527,  0.        ]])

In [12]:
A2[[0,2]][:,[0,2]]

array([[ 0.        , -0.01555483],
       [ 0.01555483,  0.        ]])

In [13]:
#Question 3(c) - Stochastic matrix(Right stochastic matrix, sum of rows =1)
A3 = A/A.sum(axis=1)[:,None]
A3

array([[0.39606859, 0.37306911, 0.2308623 ],
       [0.33973207, 0.54730467, 0.11296326],
       [0.24523567, 0.5755862 , 0.17917813]])

In [14]:
A3[[0,2]][:,[0,2]]

array([[0.39606859, 0.2308623 ],
       [0.24523567, 0.17917813]])

In [18]:
#Question 3(d) - Hankel Matrix
import scipy as sp
from scipy import linalg
A4 = sp.linalg.hankel([1,2,3],[3,4,5])
A4

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [19]:
A4[[0,2]][:,[0,2]]

array([[1, 3],
       [3, 5]])

# QUESTION 4

In [21]:
A5 = np.array([(1,-1,0,1,3),(2,3,-1,-4,4),(1,0,1,1,-2)])
A5

array([[ 1, -1,  0,  1,  3],
       [ 2,  3, -1, -4,  4],
       [ 1,  0,  1,  1, -2]])

In [22]:
D = A5.T
D

array([[ 1,  2,  1],
       [-1,  3,  0],
       [ 0, -1,  1],
       [ 1, -4,  1],
       [ 3,  4, -2]])

In [23]:
#Question 4(a) 
mean = np.mean(D,axis=1) #mean
mean

array([ 1.33333333,  0.66666667,  0.        , -0.66666667,  1.66666667])

In [25]:
st_dev = np.std(D,axis=1) #standard deviation
st_dev

array([0.47140452, 1.69967317, 0.81649658, 2.3570226 , 2.62466929])

In [33]:
#Question 4(b) #nearest neighbour
nearest_neighbour = D[np.argmin(np.linalg.norm(D-np.array([1,1,1]),axis=1))]
nearest_neighbour

array([1, 2, 1])